spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://129.211.129.48:3306/test?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull
    username: root
    password: itnsf8888
    type: com.alibaba.druid.pool.DruidDataSource




mybatis:
  #  mapper.xml的位置
  mapper-locations: classpath:/mapper/*.xml